# Car Price Prediction::

In [65]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [66]:
cd /content/drive/MyDrive/AI-Assignments

/content/drive/MyDrive/AI-Assignments


Download dataset from this link:

https://www.kaggle.com/hellbuoy/car-price-prediction

# Problem Statement::

A Chinese automobile company Geely Auto aspires to enter the US market by setting up their manufacturing unit there and producing cars locally to give competition to their US and European counterparts.

They have contracted an automobile consulting company to understand the factors on which the pricing of cars depends. Specifically, they want to understand the factors affecting the pricing of cars in the American market, since those may be very different from the Chinese market. The company wants to know:

Which variables are significant in predicting the price of a car
How well those variables describe the price of a car
Based on various market surveys, the consulting firm has gathered a large data set of different types of cars across the America market.

# task::
We are required to model the price of cars with the available independent variables. It will be used by the management to understand how exactly the prices vary with the independent variables. They can accordingly manipulate the design of the cars, the business strategy etc. to meet certain price levels. Further, the model will be a good way for management to understand the pricing dynamics of a new market.

# WORKFLOW ::

1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

4.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

5.Compilation Step (Note : Its a Regression problem , select loss , metrics according to it)
6.Train the Model with Epochs (100) and validate it

7.If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .

8.Evaluation Step

9.Prediction

In [67]:
import pandas as pd
import numpy as np
car_data=pd.read_csv('./CarPrice_Assignment.csv')

In [68]:
import tensorflow as tf

In [69]:
car_data

car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]

In [70]:
car_data.drop(columns=["car_ID","CarName"],inplace=True)


In [71]:
car_data.columns

Index(['symboling', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'wheelbase', 'carlength', 'carwidth',
       'carheight', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize',
       'fuelsystem', 'boreratio', 'stroke', 'compressionratio', 'horsepower',
       'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object')

In [72]:
car_data.dtypes

symboling             int64
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [73]:
final_car=pd.get_dummies(car_data,columns=["symboling","fueltype","aspiration","doornumber","carbody","drivewheel","enginelocation","enginetype","cylindernumber","fuelsystem"])

In [74]:
final_car.head()

wheelbase  carlength  ...  fuelsystem_spdi  fuelsystem_spfi
0       88.6      168.8  ...                0                0
1       88.6      168.8  ...                0                0
2       94.5      171.2  ...                0                0
3       99.8      176.6  ...                0                0
4       99.4      176.6  ...                0                0

[5 rows x 58 columns]

In [75]:
len(final_car)

205

In [76]:
ss=np.random.rand(205)

In [77]:
ss

array([0.83340657, 0.17920027, 0.87799827, 0.3665577 , 0.10370052,
       0.99571466, 0.66586556, 0.38014734, 0.35779752, 0.99575002,
       0.05894588, 0.41331817, 0.70924264, 0.00505124, 0.54393771,
       0.07019209, 0.86425411, 0.62878446, 0.99255921, 0.40620314,
       0.06242704, 0.2387106 , 0.41499991, 0.24522962, 0.98751745,
       0.41488746, 0.50728638, 0.60942492, 0.24209534, 0.61286695,
       0.20259731, 0.89586917, 0.45898822, 0.49036046, 0.57336176,
       0.93243052, 0.60452269, 0.58107377, 0.50258185, 0.24372606,
       0.03895346, 0.46416106, 0.6818842 , 0.46840229, 0.65017206,
       0.43015167, 0.49438827, 0.39388586, 0.86136648, 0.59892069,
       0.08928522, 0.61521538, 0.73378041, 0.43548401, 0.74900459,
       0.67864659, 0.25034432, 0.32652129, 0.37184091, 0.58912419,
       0.44657106, 0.77722514, 0.33458203, 0.58296343, 0.31552225,
       0.46936004, 0.32268929, 0.22165187, 0.55560586, 0.75613387,
       0.92824035, 0.24744723, 0.92911832, 0.88989176, 0.62559

In [78]:
np.random.seed(224)
msk=np.random.randn(len(final_car))<0.72
train_total=final_car[msk]
test_total=final_car[~msk]

In [79]:
print(len(train_total))
print(len(test_total))

154
51


In [80]:
train_label=train_total.loc[:,"price"]
test_label=test_total.loc[:,"price"]

In [81]:
train_label

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...   
196    15985.0
198    18420.0
200    16845.0
202    21485.0
204    22625.0
Name: price, Length: 154, dtype: float64

In [82]:
test_label

5      15250.0
7      18920.0
17     36880.0
22      6377.0
29     12964.0
30      6479.0
31      6855.0
38      9095.0
41     12945.0
42     10345.0
45      8916.5
46     11048.0
51      6095.0
52      6795.0
61     10595.0
62     10245.0
65     18280.0
66     18344.0
69     28176.0
73     40960.0
75     16503.0
81      8499.0
87      9279.0
94      7299.0
96      7499.0
103    13499.0
106    18399.0
108    13200.0
110    13860.0
119     7957.0
122     7609.0
126    32528.0
128    37028.0
133    12170.0
137    18620.0
141     7126.0
146     7463.0
162     9258.0
166     9538.0
167     8449.0
170    11199.0
177    11248.0
178    16558.0
179    15998.0
188     9995.0
189    11595.0
191    13295.0
197    16515.0
199    18950.0
201    19045.0
203    22470.0
Name: price, dtype: float64

In [83]:
train_data=train_total.drop(columns=["price"])
test_data=test_total.drop(columns=["price"])

In [84]:
train_data.shape

(154, 57)

In [85]:
test_data.shape

(51, 57)

In [86]:
{train_data.columns.get_loc(c): c for idx, c in enumerate(train_data.columns)}

{0: 'wheelbase',
 1: 'carlength',
 2: 'carwidth',
 3: 'carheight',
 4: 'curbweight',
 5: 'enginesize',
 6: 'boreratio',
 7: 'stroke',
 8: 'compressionratio',
 9: 'horsepower',
 10: 'peakrpm',
 11: 'citympg',
 12: 'highwaympg',
 13: 'symboling_-2',
 14: 'symboling_-1',
 15: 'symboling_0',
 16: 'symboling_1',
 17: 'symboling_2',
 18: 'symboling_3',
 19: 'fueltype_diesel',
 20: 'fueltype_gas',
 21: 'aspiration_std',
 22: 'aspiration_turbo',
 23: 'doornumber_four',
 24: 'doornumber_two',
 25: 'carbody_convertible',
 26: 'carbody_hardtop',
 27: 'carbody_hatchback',
 28: 'carbody_sedan',
 29: 'carbody_wagon',
 30: 'drivewheel_4wd',
 31: 'drivewheel_fwd',
 32: 'drivewheel_rwd',
 33: 'enginelocation_front',
 34: 'enginelocation_rear',
 35: 'enginetype_dohc',
 36: 'enginetype_dohcv',
 37: 'enginetype_l',
 38: 'enginetype_ohc',
 39: 'enginetype_ohcf',
 40: 'enginetype_ohcv',
 41: 'enginetype_rotor',
 42: 'cylindernumber_eight',
 43: 'cylindernumber_five',
 44: 'cylindernumber_four',
 45: 'cylind

In [87]:
mean = train_data.iloc[:,0:13].mean(axis=0)
train_data.iloc[:,0:13] -= mean
std = train_data.iloc[:,0:13].std(axis=0)
train_data.iloc[:,0:13] /= std
test_data.iloc[:,0:13] -= mean
test_data.iloc[:,0:13] /= std

In [88]:
mean_label = train_label.mean()
train_label -= mean_label
std_label = train_label.std()
train_label /= std_label
test_label -= mean_label
test_label /= std_label

In [89]:
train_data.shape

(154, 57)

In [90]:
test = np.array(test_data.iloc[:])

In [91]:
train = np.array(train_data.iloc[:])

In [92]:
test_l= np.array(test_label.astype('float32'))

In [93]:
train_l= np.array(train_label.astype('float32'))

In [94]:
from keras import models
from keras import layers
def build_model(act):
  model = models.Sequential()
  model.add(layers.Dense(10, activation= act,input_shape=(train.shape[1],)))
  model.add(layers.Dense(8, activation= act))
  model.add(layers.Dense(6, activation= act))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [95]:
build_model('relu').summary()

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_80 (Dense)             (None, 10)                580       
_________________________________________________________________
dense_81 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_82 (Dense)             (None, 6)                 54        
_________________________________________________________________
dense_83 (Dense)             (None, 1)                 7         
Total params: 729
Trainable params: 729
Non-trainable params: 0
_________________________________________________________________


In [96]:
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_relu = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model('relu')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=1)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=1)
  all_scores_relu.append(val_mae)

processing fold # 0
Epoch 1/100
116/116 [==============================] - 1s 998us/step - loss: 0.5669 - mae: 0.5955
Epoch 2/100
116/116 [==============================] - 0s 1ms/step - loss: 0.3572 - mae: 0.3904
Epoch 3/100
116/116 [==============================] - 0s 1ms/step - loss: 0.3499 - mae: 0.3266
Epoch 4/100
116/116 [==============================] - 0s 2ms/step - loss: 0.1512 - mae: 0.2257
Epoch 5/100
116/116 [==============================] - 0s 1ms/step - loss: 0.1888 - mae: 0.2412
Epoch 6/100
116/116 [==============================] - 0s 981us/step - loss: 0.1135 - mae: 0.2010
Epoch 7/100
116/116 [==============================] - 0s 1ms/step - loss: 0.0944 - mae: 0.1786
Epoch 8/100
116/116 [==============================] - 0s 1ms/step - loss: 0.1093 - mae: 0.1776
Epoch 9/100
116/116 [==============================] - 0s 1ms/step - loss: 0.0434 - mae: 0.1438
Epoch 10/100
116/116 [==============================] - 0s 1ms/step - loss: 0.0424 - mae: 0.1234
Epoch 11/100
11

In [97]:
all_scores_relu

[0.4000256657600403,
 0.27187779545783997,
 0.3326493203639984,
 0.3701492249965668]

In [98]:
model_relu = build_model('relu')
model_relu.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test, test_l)

2/2 [==============================] - 0s 5ms/step - loss: 0.1073 - mae: 0.2358


In [99]:
x_relu = model_relu.predict(test[1].reshape(1,test.shape[1]))

In [100]:
x_relu

array([[0.4320789]], dtype=float32)

In [101]:
test_l[1]

0.7551164

In [102]:
x_relu * std_label + mean_label

array([[16363.85]], dtype=float32)