# Credit Card Fraud Detection::

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd/content/drive/MyDrive/AI-Assignments

/content/drive/MyDrive/AI-Assignments


Download dataset from this link:

https://www.kaggle.com/mlg-ulb/creditcardfraud

# Description about dataset::

The datasets contains transactions made by credit cards in September 2013 by european cardholders.
This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, … V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning. 


### Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.

# WORKFLOW :

1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Standardized the Input Variables. 

4.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

5.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

6.Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)

7.Train the Model with Epochs (100).

8.If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .

9.Prediction should be > 92%
10.Evaluation Step
11Prediction


# Task::

## Identify fraudulent credit card transactions.

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [4]:
credit=pd.read_csv('./creditcard.csv')

In [5]:
credit.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [6]:
credit.isnull().any()

Time      False
V1        False
V2        False
V3        False
V4        False
V5        False
V6        False
V7        False
V8        False
V9        False
V10       False
V11       False
V12       False
V13       False
V14       False
V15       False
V16       False
V17       False
V18       False
V19       False
V20       False
V21       False
V22       False
V23       False
V24       False
V25       False
V26       False
V27       False
V28       False
Amount    False
Class     False
dtype: bool

In [7]:
np.where(credit.applymap(lambda x:x == ''))

(array([], dtype=int64), array([], dtype=int64))

In [8]:
credit.describe()

Time            V1  ...         Amount          Class
count  284807.000000  2.848070e+05  ...  284807.000000  284807.000000
mean    94813.859575  3.919560e-15  ...      88.349619       0.001727
std     47488.145955  1.958696e+00  ...     250.120109       0.041527
min         0.000000 -5.640751e+01  ...       0.000000       0.000000
25%     54201.500000 -9.203734e-01  ...       5.600000       0.000000
50%     84692.000000  1.810880e-02  ...      22.000000       0.000000
75%    139320.500000  1.315642e+00  ...      77.165000       0.000000
max    172792.000000  2.454930e+00  ...   25691.160000       1.000000

[8 rows x 31 columns]

In [9]:
amount_zero=np.where(credit.Amount.apply(lambda x:x == 0))

In [10]:
amount_zero

(array([   383,    514,    534, ..., 283949, 284085, 284770]),)

In [11]:
(credit["Amount"].values==0).sum()  # To check total number of zero in amount column of credit

1825

In [12]:
np.random.seed(123)
mask=np.random.rand(len(credit))<0.7
train=credit[mask]
test=credit[~mask]

In [13]:
print(train.shape)
print(test.shape)

(199077, 31)
(85730, 31)


In [14]:
train_label=train.iloc[:,-1]
test_label=test.iloc[:,-1]

In [15]:
print(train_label.shape)
print(test_label.shape)

(199077,)
(85730,)


In [16]:
train_data=train.drop(columns="Class")

In [17]:
train_data.head()

Time        V1        V2        V3  ...       V26       V27       V28  Amount
0   0.0 -1.359807 -0.072781  2.536347  ... -0.189115  0.133558 -0.021053  149.62
1   0.0  1.191857  0.266151  0.166480  ...  0.125895 -0.008983  0.014724    2.69
2   1.0 -1.358354 -1.340163  1.773209  ... -0.139097 -0.055353 -0.059752  378.66
3   1.0 -0.966272 -0.185226  1.792993  ... -0.221929  0.062723  0.061458  123.50
5   2.0 -0.425966  0.960523  1.141109  ...  0.105915  0.253844  0.081080    3.67

[5 rows x 30 columns]

In [18]:
test_data=test.drop(columns="Class")

In [19]:
test_data.head()

Time        V1        V2        V3  ...       V26       V27       V28  Amount
4    2.0 -1.158233  0.877737  1.548718  ...  0.502292  0.219422  0.215153   69.99
6    4.0  1.229658  0.141004  0.045371  ... -0.257237  0.034507  0.005168    4.99
11  10.0  0.384978  0.616109 -0.874300  ... -0.492208  0.042472 -0.054337    9.99
15  12.0 -0.752417  0.345485  2.057323  ... -0.087086 -0.180998  0.129394   15.99
21  17.0  0.962496  0.328461 -0.171479  ...  0.199964  0.016371 -0.014605   34.09

[5 rows x 30 columns]

In [20]:
mean=train_data.mean(axis=0)
train_data-=mean
std=train_data.std(axis=0)
train_data/=std
test_data-=mean
test_data/=std

In [21]:
train_data.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
dtype: object

In [22]:
test_data.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
dtype: object

In [78]:
from keras import models,layers

In [79]:
model= models.Sequential()
model.add(layers.Dense(10, activation="relu", input_shape=(train_data.shape[1],)))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(8, activation="relu"))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(6,activation="relu"))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(1,activation="sigmoid"))
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(train_data, train_label, epochs=100, validation_split=.3, validation_batch_size=150, validation_steps=10)

Epoch 1/100
4355/4355 [==============================] - 7s 2ms/step - loss: 0.0718 - accuracy: 0.9947 - val_loss: 0.0013 - val_accuracy: 0.9993
Epoch 2/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0035 - accuracy: 0.9992 - val_loss: 9.0794e-04 - val_accuracy: 1.0000
Epoch 3/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0035 - accuracy: 0.9991 - val_loss: 8.5451e-04 - val_accuracy: 1.0000
Epoch 4/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0031 - accuracy: 0.9993 - val_loss: 0.0012 - val_accuracy: 1.0000
Epoch 5/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0027 - accuracy: 0.9994 - val_loss: 0.0010 - val_accuracy: 1.0000
Epoch 6/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0027 - accuracy: 0.9994 - val_loss: 5.3454e-04 - val_accuracy: 1.0000
Epoch 7/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0027 - accuracy: 0.9993 - val_loss: 8.1

In [32]:
# validation_split taken as 0.3

In [ ]:
0.2*len(credit)

In [ ]:
0.2*len(credit)/len(train_data)

In [80]:
loss, accuracy=model.evaluate(test_data,test_label)

2680/2680 [==============================] - 3s 1ms/step - loss: 0.0073 - accuracy: 0.9993


In [83]:
model.predict(np.array(test_data.iloc[1,:]).reshape(1,test_data.shape[1]))

array([[1.864473e-11]], dtype=float32)

In [84]:
predicted_value=model.predict(test_data)

In [85]:
max(predicted_value)

array([1.], dtype=float32)

In [86]:
min(predicted_value)

array([0.], dtype=float32)

In [96]:
np.count_nonzero(predicted_value==1)

68

In [97]:
np.count_nonzero(predicted_value==0)

312

In [101]:
np.count_nonzero(predicted_value>1)

0

In [102]:
np.count_nonzero(test_label==1)

145